---
title: 'Metodología de Remuestreo'
author: "Lizeth Llanos/ Diego Agudelo"
date: "4/20/2020"
output: 
 html_document:
    theme: lumen
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    highlight: tango
---

```{r MODIFICAR, include=FALSE}
# Aqui se modifican las siguientes líneas

year_forecast <- 2020 ### Año del pronóstico
localidad <- "Sitio_A" ### Nombre del sitio

directorio <- "D:/OneDrive - CGIAR/Desktop/resampling" ### Este es el directorio donde se tienen los archivos de entrada y donde se guardarán los resultados

nasa_power <- TRUE ### Si desea descargar los datos diarios de NASA POWER ponga TRUE. Si ud desea trabajar con datos observados ponga FALSE

# latitud y longitud solo son necesarios si va a usar datos de NASA Power, de lo contrario puede omitirlos
latitud   <- 4.6    ### Latitud del sitio de interés(en grados decimales)
longitud  <- -76   ### Longitud del sitio de interés(en grados decimales)
```









```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

```

# Carga de los inputs

Aquí se cargan los archivos de entrada:
-Probabilidades
-Datos históricos

```{r nasa, include=FALSE}
directorio_datos <- paste0(directorio, "/data/")
directorio_resultados <- paste0(directorio, "/resultados/")

source("https://raw.githubusercontent.com/lizllanos/foro-clim-resampling/master/donwload_nasa_daily.R", encoding = "UTF-8")

object_empty <- download_nasa(main_dir,start_date,end_date,latitud,longitud)

```



```{r, include=F}

## Read Data
pos<-which(grepl('data', list.files(directorio_datos))==T)[1]
pos1<-which(grepl('pronostico', list.files(directorio_datos))==T)[1]

data_historic <- read_csv(list.files(directorio_datos, full.names =T)[pos]) %>% 
  rename(prec = precip) 

pronostico <- read_csv(list.files(directorio_datos, full.names =T)[pos1])

```


# Pronóstico probabilistico

Aquí se observa el pronóstico

```{r pressure, echo=FALSE}
as.data.frame(pronostico)
plot_prob(pronostico)

```

# Análisis del clima histórico
Aquí se observa el comportamiento histórico del clima

```{r, echo=FALSE}
head(as.data.frame(data_historic), 10)

plot_clima_hist(data_historic, localidad)

```

# Remuestreo

Aquí ya se corre el remuestreo
```{r, echo=FALSE}
source("https://raw.githubusercontent.com/lizllanos/foro-clim-resampling/master/resampling.R", encoding = "UTF-8")

data_resampling <- resampling(data_historic, pronostico, year_forecast)
plot_resampling(data_resampling, data_historic, localidad)

## Save escenaries(Opcional)
dir.create(directorio_resultados)
function_to_save(localidad, data_resampling, directorio_resultados)

```

